mapnowrm = nan(1,nregs+1); % regional mean po4 at 200 m
for ireg=1:nregs
    mapnowrm(ireg) = ...
        nansum(mapnow(reg_map==ireg).*area_ocn_only(reg_map==ireg))...
        ./nansum(area_ocn_only(reg_map==ireg));
end
mapnowrm(end) = nansum(nansum(mapnow.*area_ocn_only))...
    /tot_ocn_area;
