hatchedbars = hatchfill2(...
    hatchedbars,'hatchstyle','single','hatchangle',45,...
    'hatchdensity',15,'hatchcolor',[0 0 0.8],'hatchlinewidth',2);
set(hatchedbars(1),'color',colornow,'linewidth',1.5);
set(solidbars(1),'facecolor',colornow);
